# DB setting
spring:
  datasource:
    url: jdbc:mysql://ls-327224baba253ec8fc168adcdb1688a8be5f5647.clmym0ek09ts.ap-northeast-2.rds.amazonaws.com:3306/todo?useUnicode=true&characterEncoding=UTF-8&characterSetResult=UTF-8&useSSL=true
    username: todoadmin
    password: todopassword

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security.web: trace  # 시큐리티 관련 로그 남기기

server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie